### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by wvdvegt** [e-ucm/unity-tracker#12]
The line in XApiFormat.cs

60 extensionsChild.Add (EXT_PREFIX + "value", parts [3]); 

Seems to be incompatible with Click traces (they have 3 or 4 parameters of which last one can be a target, which is ignored for xApi traces). 

Target is expected as part of the object id url value.
Both x and y are result values and can only end-up in the object result value of an xAPI statement (like X.Y).

**Comment by manuel-freire** [comment]
Using the newer xAPI serious-games recipe, the event model is due to change completely.
