### ISSUE TITLE
Tracking Flow

### ISSUE THREAD

**Issue by wvdvegt** [e-ucm/unity-tracker#7]
Hi

As a number of essential variables are removed from the code (like host and trackingCode) and the code is not that easy to follow without recreating the game, I would like to see a short description of how to track things and where to get values like the tracking code from.

So could you please provide a short description of which rest  calls to make and what parameters, headers and body are required. 

I know it overlaps with text in the front-end api documentation but there the flow is not clearly documented (or i missed it completely).

Best Regards
Wim van der Vegt

**Comment by manuel-freire** [comment]
This project makes all its rest calls using Unity5 facilities. 

It does not make sense to duplicate exact request documentation here, as the requirement is that the messages conform to whatever the server expects to receive, as documented in  the [rage-analytics-backend API](http://e-ucm.github.io/rage-analytics-backend/). Note that messages must be proxied via a2 - the exact end-points are described [here](https://github.com/e-ucm/rage-analytics-backend/blob/master/a-backend-roles.js). When roles are listed, they require previous authentication with an A2 user that has the correct role; this can be achieved with a [login request](http://e-ucm.github.io/a2/#api-Login-Login)

To see  the exact messages sent when communicating to the server, a fail-safe approach is to launch the [demo game](https://github.com/e-ucm/QuizDemo) and look at the message contents with a network analyzer such as [WireShark](https://www.wireshark.org/) (or, if playing the game in a browser, the browser's in-built HTTP analyzer).

It makes no sense to include either `host` or `trackingCode` in the unity-tracker code, as these must be supplied to each game when the game is deployed (and therefore will be different for each deployment of a given game; all of which will be sharing the same unity-tracker code).

I am closing this issue, as it does not, as we understand it, describe a problem or missing feature in the unity-tracker project itself. If the documentation in either the rage-analytics-backend or a2 is unclear, then please file an issue in any of these projects, describing the problem as clearly as possible.
